alias lsop="lsof -i"
alias yai="ylock"
alias yall="yall"
alias yas="yarn"
alias gid="git diff"
alias gdd="git add"
alias gis="git status"
alias gip="git push"
alias gic="git cz"
alias gio="git"
alias gim="git commit -m"
alias kila="kill -9"
alias vim=nvim
alias la='ls -la'
alias pqp="python3"
alias python="python3"
alias idea="/Applications/IntelliJ\ IDEA.app/Contents/MacOS/idea"
alias web="/Applications/WebStorm.app/Contents/MacOS/webstorm"
alias pn="pnpm"
alias gtf="git"
alias gtt="git"
alias ghc="git"
alias gty="git"
alias gtd="git"
alias lsop="lsof"
alias kila="kill -9"
alias pnd="pnpm"
alias nxg="nxg"
alias work1='cd /Volumes/Best_Photo; echo "🚀 Moved to /Volumes/Best Photo"'
alias work='cd /Volumes/Work; echo "🚀 Moved to /Volumes/Work"'
alias open_config='code ~/.config'


