#!/usr/bin/env fish
# ==============================================================================
# Add Custom Abbreviation
# ==============================================================================
# Function to add personal abbreviations and save them
# Usage: abbr_add <name> <expansion>
# Example: abbr_add gpp "git pull && git push"
# ==============================================================================

function abbr_add --description "Add a custom abbreviation and save it permanently"
    # Check if the correct number of arguments is provided
    if test (count $argv) -lt 2
        echo "Usage: abbr_add <name> <expansion>"
        echo "Example: abbr_add gpp 'git pull && git push'"
        return 1
    end

    set -l abbr_name $argv[1]
    set -l abbr_expansion $argv[2..-1]
    set -l abbr_file ~/.config/fish/personalized/abbreviations.fish

    # Create the personalized directory if it doesn't exist
    if not test -d ~/.config/fish/personalized
        mkdir -p ~/.config/fish/personalized
    end

    # Create the abbreviations file if it doesn't exist
    if not test -f $abbr_file
        echo "# Custom Abbreviations" > $abbr_file
        echo "# Auto-generated by abbr_add function" >> $abbr_file
        echo "" >> $abbr_file
    end

    # Add the abbreviation to the current session
    abbr -a $abbr_name $abbr_expansion

    # Save to file (check if it already exists)
    if grep -q "abbr -a $abbr_name " $abbr_file
        echo "⚠️  Abbreviation '$abbr_name' already exists in $abbr_file"
        echo "Current expansion: "(abbr --show | grep "^abbr -a $abbr_name " | sed "s/abbr -a $abbr_name //")
        echo "New expansion: $abbr_expansion"
        read -P "Overwrite? [y/N] " -l confirm

        if test "$confirm" = "y" -o "$confirm" = "Y"
            # Remove old abbreviation and add new one
            sed -i '' "/abbr -a $abbr_name /d" $abbr_file
            echo "abbr -a $abbr_name \"$abbr_expansion\"" >> $abbr_file
            echo "✅ Abbreviation '$abbr_name' updated!"
        else
            echo "❌ Abbreviation not updated."
            return 1
        end
    else
        # Add new abbreviation
        echo "abbr -a $abbr_name \"$abbr_expansion\"" >> $abbr_file
        echo "✅ Abbreviation '$abbr_name' added!"
    end

    echo "📝 Expansion: $abbr_expansion"
    echo "💾 Saved to: $abbr_file"
end
