function fish_backup_help --description 'Show fish backup system quick reference'
    echo ""
    echo "Fish Configuration Backup System - Quick Reference"
    echo "==================================================="
    echo ""
    echo "BACKUP FUNCTIONS:"
    echo "  backup_fish_config              Create backup of current config"
    echo "  restore_fish_config [tag/hash]  Restore from backup"
    echo "  snapshot_fish_config [name]     Create tagged snapshot"
    echo "  list_fish_snapshots             List all backups"
    echo "  toggle_fish_autobackup [cmd]    Manage auto-backup (enable/disable/status)"
    echo ""
    echo "QUICK START:"
    echo "  1. Create first backup:   backup_fish_config"
    echo "  2. List all backups:      list_fish_snapshots"
    echo "  3. Restore if needed:     restore_fish_config"
    echo ""
    echo "AUTO-BACKUP:"
    echo "  Enable:   toggle_fish_autobackup enable"
    echo "  Status:   toggle_fish_autobackup status"
    echo "  Disable:  toggle_fish_autobackup disable"
    echo ""
    echo "AGENT SAFETY:"
    echo "  Before changes:  snapshot_fish_config agent-task"
    echo "  After changes:   backup_fish_config"
    echo "  If problems:     restore_fish_config [tag]"
    echo ""
    echo "DOCUMENTATION:"
    echo "  Full docs: ~/.config/fish/BACKUP_SYSTEM.md"
    echo "  Status:    ~/.config/fish/hooks/BACKUP_STATUS.txt"
    echo ""
    echo "SAFETY:"
    echo "  ✓ fish_variables is NEVER backed up (contains secrets)"
    echo "  ✓ Restore asks confirmation if uncommitted changes exist"
    echo "  ✓ All backups are LOCAL (not pushed to remote)"
    echo ""
end
