function session_help -d "Display help for session management commands"
    set -l command $argv[1]

    if test -z "$command"
        echo "Fish Shell Session Management"
        echo "=============================="
        echo ""
        echo "Commands:"
        echo "  session_save           Save current session state"
        echo "  session_restore        Restore a saved session"
        echo "  session_list           List all saved sessions"
        echo "  session_delete         Delete a session"
        echo "  session_diff           Compare session with current state"
        echo "  session_export         Export session to other formats"
        echo "  session_template       Manage session templates"
        echo "  session_autosave_*     Auto-save configuration"
        echo ""
        echo "Usage: session_help <command>"
        echo "Example: session_help session_save"
        echo ""
        echo "Quick Start:"
        echo "  session_save my-work        # Save current state"
        echo "  session_restore my-work     # Restore later"
        echo "  session_list                # View all sessions"
        echo ""
        echo "Documentation: ~/.config/fish/sessions/README.md"
        echo "Quick Reference: ~/.config/fish/sessions/QUICKREF.md"
        return 0
    end

    switch $command
        case session_save save
            echo "session_save - Save current terminal session"
            echo ""
            echo "USAGE:"
            echo "  session_save [name]"
            echo "  session_save -n <name>"
            echo "  session_save --auto <name>"
            echo ""
            echo "OPTIONS:"
            echo "  -n, --name <name>    Session name (default: directory name)"
            echo "  -a, --auto           Mark as auto-saved (internal use)"
            echo ""
            echo "WHAT GETS SAVED:"
            echo "  - Working directory"
            echo "  - Environment variables (non-sensitive)"
            echo "  - Command history (last 50 commands)"
            echo "  - Git branch information"
            echo "  - Tmux session info"
            echo ""
            echo "EXAMPLES:"
            echo "  session_save                # Use directory name"
            echo "  session_save my-project     # Custom name"
            echo "  session_save -n backend     # With flag"

        case session_restore restore
            echo "session_restore - Restore a saved session"
            echo ""
            echo "USAGE:"
            echo "  session_restore <name>"
            echo "  session_restore -n <name>"
            echo "  session_restore --no-cd <name>"
            echo ""
            echo "OPTIONS:"
            echo "  -n, --name <name>    Session name to restore"
            echo "  --no-cd              Don't change directory"
            echo ""
            echo "EXAMPLES:"
            echo "  session_restore my-project      # Full restore"
            echo "  session_restore --no-cd proj    # Keep current dir"

        case session_list list ls
            echo "session_list - List all saved sessions"
            echo ""
            echo "USAGE:"
            echo "  session_list"
            echo "  session_list -l"
            echo "  session_list -j"
            echo ""
            echo "OPTIONS:"
            echo "  -l, --long    Show detailed information"
            echo "  -j, --json    Output in JSON format"
            echo ""
            echo "EXAMPLES:"
            echo "  session_list       # Simple list"
            echo "  session_list -l    # Detailed view"
            echo "  session_list -j    # JSON output"

        case session_delete delete rm
            echo "session_delete - Delete a saved session"
            echo ""
            echo "USAGE:"
            echo "  session_delete <name>"
            echo "  session_delete -f <name>"
            echo ""
            echo "OPTIONS:"
            echo "  -n, --name <name>    Session name to delete"
            echo "  -f, --force          Skip confirmation"
            echo ""
            echo "EXAMPLES:"
            echo "  session_delete old-project      # With confirmation"
            echo "  session_delete -f old-project   # Force delete"

        case session_template template
            echo "session_template - Manage session templates"
            echo ""
            echo "USAGE:"
            echo "  session_template -l"
            echo "  session_template -c <name>"
            echo "  session_template -a <name>"
            echo ""
            echo "OPTIONS:"
            echo "  -l, --list           List available templates"
            echo "  -c, --create <name>  Create new template"
            echo "  -a, --apply <name>   Apply a template"
            echo ""
            echo "BUILT-IN TEMPLATES:"
            echo "  nodejs    Node.js development"
            echo "  python    Python development"
            echo "  rust      Rust development"
            echo "  web-dev   Full-stack web development"
            echo ""
            echo "EXAMPLES:"
            echo "  session_template -l              # List templates"
            echo "  session_template -a nodejs       # Apply Node.js template"
            echo "  session_template -c mytemplate   # Create custom template"

        case session_diff diff
            echo "session_diff - Compare session with current state"
            echo ""
            echo "USAGE:"
            echo "  session_diff <name>"
            echo ""
            echo "EXAMPLES:"
            echo "  session_diff my-project"

        case session_export export
            echo "session_export - Export session to portable format"
            echo ""
            echo "USAGE:"
            echo "  session_export -n <name> [-f format] [-o file]"
            echo ""
            echo "OPTIONS:"
            echo "  -n, --name <name>      Session name"
            echo "  -f, --format <format>  Output format (bash, zsh, json)"
            echo "  -o, --output <file>    Output file path"
            echo ""
            echo "EXAMPLES:"
            echo "  session_export -n proj -f bash -o setup.sh"
            echo "  session_export -n proj -f json"

        case autosave auto
            echo "Session Auto-Save Functions"
            echo ""
            echo "session_autosave_enable"
            echo "  Enable automatic session saving on shell exit"
            echo ""
            echo "session_autosave_disable"
            echo "  Disable automatic session saving"
            echo ""
            echo "session_autosave_name <name>"
            echo "  Set default session name for auto-save"
            echo ""
            echo "EXAMPLES:"
            echo "  session_autosave_enable"
            echo "  session_autosave_name daily-work"
            echo "  session_autosave_disable"

        case '*'
            echo "Unknown command: $command"
            echo "Run 'session_help' for list of available commands"
            return 1
    end

    return 0
end
