# Custom Abbreviations
# Auto-generated by abbr_add function
# Add your personal abbreviations here using: abbr_add <name> <expansion>

# Example custom abbreviations (uncomment to use):
# abbr -a gpp "git pull && git push"
# abbr -a deploy "npm run build && npm run deploy"
# abbr -a mywork "cd ~/Work && code ."
