# Dracula Color Palette
export DRACULA_BACKGROUND="#282a36"
export DRACULA_FOREGROUND="#f8f8f2"
export DRACULA_SELECTION="#44475a"
export DRACULA_COMMENT="#6272a4"
export DRACULA_CYAN="#8be9fd"
export DRACULA_GREEN="#50fa7b"
export DRACULA_ORANGE="#ffb86c"
export DRACULA_PINK="#ff79c6"
export DRACULA_PURPLE="#bd93f9"
export DRACULA_RED="#ff5555"
export DRACULA_YELLOW="#f1fa8c"

# LS_COLORS with Dracula theme
export LS_COLORS="di=$DRACULA_CYAN:ln=$DRACULA_PURPLE:so=$DRACULA_PINK:pi=$DRACULA_YELLOW:ex=$DRACULA_GREEN:bd=$DRACULA_ORANGE:cd=$DRACULA_ORANGE:su=$DRACULA_RED:sg=$DRACULA_RED:tw=$DRACULA_CYAN:ow=$DRACULA_CYAN"
